version: "3.8"

services:
  backend:
    image: ttttkii91333/devdo2
    container_name: devdo2
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

  redis:
    image: redis:7.2
    container_name: devdo2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
